language: cpp
env:
- TEST_SUITE=unit_tests
compiler:
  - gcc
matrix:
  include:
    # build on osx
    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="brew update && brew install gcc && CC=gcc-7 && CXX=g++-7"
    # build on ubuntu
    - os: linux
      sudo: required
      addons:
        apt:
          packages:
            - build-essential libasound2-dev libvorbisidec-dev libvorbis-dev libflac-dev alsa-utils libavahi-client-dev avahi-daemon
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
before_install:
    - eval "${MATRIX_EVAL}"
script:
  - make
  - sudo make installclient
  - sudo make installserver
